Repository softeerbootcamp-6th/Team4-PopoPony, pull requests merged in 2025-07, with the labels that each got.

#13 [FE] Setting > 프론트엔드 cursor rule 초기세팅 #5
  .cursor/rules/figma-mcp-rule.mdc
  .cursor/rules/frontend-project-structure.mdc
  .cursor/rules/frontend-typescript-rule.mdc
  .cursor/rules/frontend-used-libraries.mdc
  .gitignore
Labels: Part: 🌐 FE, Type: 📚 Docs, Priority: ⚡ Medium

#23 [FE] Common > 폴더 구조 정의 #17
  .github/ISSUE_TEMPLATE/1_main_issue.yml
  .github/ISSUE_TEMPLATE/2_be_issue.yml
  .github/ISSUE_TEMPLATE/3_fe_issue.yml
  frontend/.cta.json
  frontend/index.html
  frontend/package.json
  frontend/public/manifest.json
  frontend/src/features/auth/apis/.gitkeep
  frontend/src/features/auth/components/.gitkeep
  frontend/src/features/auth/hooks/.gitkeep
  frontend/src/features/auth/types/.gitkeep
  frontend/src/features/auth/utils/.gitkeep
  frontend/src/features/customer/apis/.gitkeep
  frontend/src/features/customer/components/.gitkeep
  frontend/src/features/customer/hooks/.gitkeep
  frontend/src/features/customer/types/.gitkeep
  frontend/src/features/customer/utils/.gitkeep
  frontend/src/features/dashboard/apis/.gitkeep
  frontend/src/features/dashboard/components/.gitkeep
  frontend/src/features/dashboard/hooks/.gitkeep
  frontend/src/features/dashboard/types/.gitkeep
  frontend/src/features/dashboard/utils/.gitkeep
  frontend/src/features/helper/apis/.gitkeep
  frontend/src/features/helper/components/.gitkeep
  frontend/src/features/helper/hooks/.gitkeep
  frontend/src/features/helper/types/.gitkeep
  frontend/src/features/helper/utils/.gitkeep
  frontend/src/routes/__root.tsx
  frontend/src/routes/customer/escort/$escortId/completed/index.tsx
  frontend/src/routes/customer/escort/$escortId/helper/$helperId/index.tsx
  frontend/src/routes/customer/escort/$escortId/index.tsx
  frontend/src/routes/customer/escort/$escortId/payment/index.tsx
  frontend/src/routes/customer/escort/$escortId/review/$reviewStep/index.tsx
  frontend/src/routes/customer/index.tsx
  frontend/src/routes/customer/recruit/$recruitStep/index.tsx
  frontend/src/routes/dashboard/$escortId/customer/index.tsx
  frontend/src/routes/dashboard/$escortId/helper/index.tsx
  frontend/src/routes/dashboard/$escortId/map/index.tsx
  frontend/src/routes/helper/application/$escortId/index.tsx
  frontend/src/routes/helper/application/completed/index.tsx
  frontend/src/routes/helper/application/index.tsx
  frontend/src/routes/helper/escort/$escortId/index.tsx
  frontend/src/routes/helper/escort/$escortId/report/$reportStep/index.tsx
  frontend/src/routes/helper/index.tsx
  frontend/src/routes/helper/profile/index.tsx
  frontend/src/routes/helper/profile/new/$newStep/index.tsx
  frontend/src/routes/login/index.tsx
  frontend/src/shared/apis/.gitkeep
  frontend/src/shared/components/.gitkeep
  frontend/src/shared/hooks/.gitkeep
  frontend/src/shared/types/.gitkeep
  frontend/src/shared/utils/.gitkeep
  frontend/tsconfig.json
Labels: Part: 🌐 FE, Type: ⚙️ Chore, Priority: 🔥 High

#28 [FE] COMMON > 버튼 컴포넌트 추가
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/routes/components/index.tsx
  frontend/src/shared/components/Button.tsx
  frontend/src/shared/components/index.ts
  frontend/src/styles.css
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#33 [FE] Common > LabeledSection, TwoOptionSelector 컴포넌트#29
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/icons/Spiner.svg
  frontend/src/assets/icons/check.svg
  frontend/src/assets/icons/index.ts
  frontend/src/routes/components/index.tsx
  frontend/src/shared/components/.gitkeep
  frontend/src/shared/components/Button.tsx
  frontend/src/shared/components/LabeledSection.tsx
  frontend/src/shared/components/Spinner.tsx
  frontend/src/shared/components/TextField/TextField_S.tsx
  frontend/src/shared/components/TwoOptionSelector.tsx
  frontend/src/shared/components/index.ts
  frontend/src/styles.css
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#41 [BE] Common > Response 공통 클래스 작성 #25
  backend/server/src/main/java/com/todoc/server/common/response/.gitkeep
  backend/server/src/main/java/com/todoc/server/common/response/ErrorResponse.java
  backend/server/src/main/java/com/todoc/server/common/response/Response.java
  backend/server/src/main/java/com/todoc/server/common/response/ResponseStatus.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High

#45 [BE] Common > Util 공통 클래스 작성 #27
  backend/server/src/main/java/com/todoc/server/common/util/.gitkeep
  backend/server/src/main/java/com/todoc/server/common/util/JsonUtil.java
  backend/server/src/test/java/com/todoc/server/common/util/JsonUtilTest.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High
