Repository softeerbootcamp-6th/Team4-PopoPony, pull requests merged in 2025-08, with the labels that each got.

#65 [FE] Home > Shadcn 설정 #55
  frontend/components.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/images/home-graphic.png
  frontend/src/routes/customer/index.tsx
  frontend/src/shared/components/Button.tsx
  frontend/src/shared/libs/utils.ts
  frontend/src/styles.css
Labels: Part: 🌐 FE, Type: ⚙️ Chore, Priority: 🔥 High

#47 [FE] Home > 랜딩 페이지 #37
  frontend/public/images/hospital.png
  frontend/public/images/landing-background.png
  frontend/public/images/work.png
  frontend/src/routes/index.tsx
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#73 [BE] [SUB] Customer > 동행 목록 조회 테스트코드 작성 #51
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitJpaRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/RecruitCreateRequest.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java
  backend/server/src/main/resources/application-local.yml
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: 🧪 Test, Priority: 🔥 High

#82 [BE] [SUB] Customer > 동행 신청하기 Service 및 DAO 계층, 테스트코드 #53
  backend/server/src/main/java/com/todoc/server/domain/auth/entity/Auth.java
  backend/server/src/main/java/com/todoc/server/domain/customer/entity/Patient.java
  backend/server/src/main/java/com/todoc/server/domain/customer/repository/PatientRepository.java
  backend/server/src/main/java/com/todoc/server/domain/customer/service/PatientService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/entity/Recruit.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/RecruitCreateRequest.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/route/entity/LocationInfo.java
  backend/server/src/main/java/com/todoc/server/domain/route/entity/Route.java
  backend/server/src/main/java/com/todoc/server/domain/route/repository/LocationInfoRepository.java
  backend/server/src/main/java/com/todoc/server/domain/route/repository/RouteRepository.java
  backend/server/src/main/java/com/todoc/server/domain/route/service/LocationInfoService.java
  backend/server/src/main/java/com/todoc/server/domain/route/service/RouteService.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitFacadeServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Type: 🧪 Test, Priority: 🔥 High

#113 [BE] [SUB] Setting > Swagger 세팅 오류 수정 #112
  backend/server/src/main/java/com/todoc/server/common/config/SwaggerConfig.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java
  backend/server/src/main/java/com/todoc/server/domain/report/web/controller/ReportController.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#121 [BE] [SUB] Setting > Deprecated 기능에 대한 soft delete 코드 수정 #120
  backend/server/src/main/java/com/todoc/server/common/entity/BaseEntity.java
  backend/server/src/main/java/com/todoc/server/domain/auth/entity/Auth.java
  backend/server/src/main/java/com/todoc/server/domain/customer/entity/Patient.java
  backend/server/src/main/java/com/todoc/server/domain/escort/entity/Application.java
  backend/server/src/main/java/com/todoc/server/domain/escort/entity/Escort.java
  backend/server/src/main/java/com/todoc/server/domain/escort/entity/Recruit.java
  backend/server/src/main/java/com/todoc/server/domain/helper/entity/Certificate.java
  backend/server/src/main/java/com/todoc/server/domain/helper/entity/Helper.java
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/entity/LatestLocation.java
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/exception/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/repository/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/service/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/controller/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/dto/request/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/dto/response/.gitkeep
  backend/server/src/main/java/com/todoc/server/domain/report/entity/ImageAttachment.java
  backend/server/src/main/java/com/todoc/server/domain/report/entity/Report.java
  backend/server/src/main/java/com/todoc/server/domain/report/entity/TaxiFee.java
  backend/server/src/main/java/com/todoc/server/domain/review/entity/PositiveFeedback.java
  backend/server/src/main/java/com/todoc/server/domain/review/entity/PositiveFeedbackChoice.java
  backend/server/src/main/java/com/todoc/server/domain/review/entity/Review.java
  backend/server/src/main/java/com/todoc/server/domain/route/entity/LocationInfo.java
  backend/server/src/main/java/com/todoc/server/domain/route/entity/Route.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#125 [BE] [SUB] Customer > 동행 리뷰 작성하기 Controller 및 DTO 작성 #86
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/dto/request/ReviewCreateRequest.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High

#130 [BE] [SUB] Customer > 동행 지원 상태값 추가 #129
  backend/server/src/main/java/com/todoc/server/common/enumeration/ApplicationStatus.java
  backend/server/src/main/java/com/todoc/server/domain/escort/entity/Application.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#124 [BE] [SUB] Setting > DTO 클래스에 NotNull 설정 #122
  backend/server/src/main/java/com/todoc/server/domain/customer/web/dto/response/PatientSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/ApplicationListResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/ApplicationSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitDetailResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitListResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitPaymentResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperDetailResponse.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperListResponse.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/report/web/dto/response/ReportDetailResponse.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/PositiveFeedbackStatResponse.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/ReviewSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/ReviewStatResponse.java
  backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/LocationInfoSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteSimpleResponse.java
Labels: Part: 🛠 BE, Type: ♻️ Refactor, Priority: ⚡ Medium

#140 [BE] [SUB] Customer > Request, Response의 Enum 필드 수정 #133
  backend/server/src/main/java/com/todoc/server/common/enumeration/ApplicationStatus.java
  backend/server/src/main/java/com/todoc/server/common/enumeration/Area.java
  backend/server/src/main/java/com/todoc/server/common/enumeration/EscortStatus.java
  backend/server/src/main/java/com/todoc/server/common/enumeration/Gender.java
  backend/server/src/main/java/com/todoc/server/common/enumeration/RecruitStatus.java
  backend/server/src/main/java/com/todoc/server/domain/customer/exception/CustomerErrorCode.java
  backend/server/src/main/java/com/todoc/server/domain/customer/exception/PatientGenderInvalidException.java
  backend/server/src/main/java/com/todoc/server/domain/customer/service/PatientService.java
  backend/server/src/main/java/com/todoc/server/domain/customer/web/dto/response/PatientSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java
  backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/ReviewSimpleResponse.java
  backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperFacadeServiceTest.java
Labels: Part: 🛠 BE, Type: ♻️ Refactor, Priority: 🔥 High

#139 [BE] [SUB] Setting > CORS 에러 해결 #136
  backend/server/src/main/java/com/todoc/server/common/config/WebConfig.java
Labels: Part: 🛠 BE, Type: ⚙️ Chore, Priority: 🔥 High

#134 [BE] [SUB] Customer > DTO에서 authId 제거 #132
  backend/server/src/main/java/com/todoc/server/domain/escort/service/ApplicationFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java
  backend/server/src/main/java/com/todoc/server/domain/helper/repository/HelperJpaRepository.java
  backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperSimpleResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/ApplicationFacadeServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitFacadeServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperFacadeServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperServiceTest.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#162 [BE] [SUB] Customer > 이전 동행 목록 불러오기 테스트코드 작성 #153
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: 🧪 Test, Priority: 🔥 High

#167 [BE] [SUB] Helper > 일감 찾기 & 지원 Service 및 DAO 계층 로직 작성 #99
  backend/server/src/main/java/com/todoc/server/common/enumeration/RecruitStatus.java
  backend/server/src/main/java/com/todoc/server/domain/escort/exception/EscortErrorCode.java
  backend/server/src/main/java/com/todoc/server/domain/escort/exception/RecruitInvalidException.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/ApplicationFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/ApplicationService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSearchListResponse.java
  backend/server/src/main/java/com/todoc/server/domain/route/exception/LocationErrorCode.java
  backend/server/src/main/java/com/todoc/server/domain/route/exception/LocationNotFoundException.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitIntegrationTest.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High

#174 [BE] [SUB] Auth > 로그인 기능 구현 #170
  backend/server/build.gradle.kts
  backend/server/src/main/java/com/todoc/server/common/config/WebConfig.java
  backend/server/src/main/java/com/todoc/server/domain/auth/exception/AuthErrorCode.java
  backend/server/src/main/java/com/todoc/server/domain/auth/exception/AuthUnAuthorizedException.java
  backend/server/src/main/java/com/todoc/server/domain/auth/repository/AuthJpaRepository.java
  backend/server/src/main/java/com/todoc/server/domain/auth/service/AuthService.java
  backend/server/src/main/java/com/todoc/server/domain/auth/service/SessionAuth.java
  backend/server/src/main/java/com/todoc/server/domain/auth/web/AuthInterceptor.java
  backend/server/src/main/java/com/todoc/server/domain/auth/web/LoginUser.java
  backend/server/src/main/java/com/todoc/server/domain/auth/web/LoginUserArgumentResolver.java
  backend/server/src/main/java/com/todoc/server/domain/auth/web/controller/AuthController.java
  backend/server/src/main/java/com/todoc/server/domain/auth/web/dto/request/LoginRequest.java
  backend/server/src/main/java/com/todoc/server/domain/auth/web/dto/response/LoginResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High

#176 [BE] [SUB] Common > Request 및 Response에서 enum 필드 수정 #175
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: ♻️ Refactor, Priority: 🔥 High

#171 [BE] [SUB] Helper > 리포트 작성 테스트코드 작성 #102
  backend/server/src/main/java/com/todoc/server/domain/report/repository/ImageAttachmentJpaRepository.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/ImageAttachmentService.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/ReportFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/ReportService.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/TaxiFeeService.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/TaxiReceiptImageService.java
  backend/server/src/test/java/com/todoc/server/domain/report/service/ReportFacadeServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/report/service/ReportIntegrationTest.java
Labels: Part: 🛠 BE, Type: 🧪 Test, Priority: 🔥 High

#184 [FE] Customer > 동행신청 POST api 연결
  frontend/src/features/customer/components/recruitStep/Communication.tsx
  frontend/src/features/customer/components/recruitStep/Condition.tsx
  frontend/src/features/customer/components/recruitStep/EscortRoute.tsx
  frontend/src/features/customer/components/recruitStep/Final.tsx
  frontend/src/features/customer/components/recruitStep/Profile.tsx
  frontend/src/features/customer/components/recruitStep/Request.tsx
  frontend/src/features/customer/components/recruitStep/Time.tsx
  frontend/src/features/customer/types/recruitFormValues.ts
  frontend/src/features/customer/utils/buildRecruitRequest.ts
  frontend/src/features/customer/utils/index.ts
  frontend/src/routes/customer/escort/$escortId/review.$step.tsx
  frontend/src/routes/helper/index.tsx
  frontend/src/shared/components/EscortCard.tsx
  frontend/src/shared/components/StatusTag.tsx
  frontend/src/shared/components/TextField/FormInput.tsx
  frontend/src/shared/components/form/PhotoUpload.tsx
  frontend/src/shared/components/form/TwoOptionSelector.tsx
  frontend/src/shared/hooks/useFormValidation.ts
  frontend/src/shared/types/api/schema.d.ts
  frontend/src/shared/types/imageType.ts
  frontend/src/shared/types/index.ts
  frontend/src/shared/utils/date.ts
  frontend/src/shared/utils/index.ts
  frontend/src/shared/utils/parseType.ts
  frontend/tsconfig.json
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#194 [FE] Auth > 로그인 & 로그인 상태 확인 #180
  frontend/src/features/auth/apis/.gitkeep
  frontend/src/features/auth/apis/getMe.ts
  frontend/src/features/auth/apis/index.ts
  frontend/src/features/auth/apis/postLogin.ts
  frontend/src/features/auth/components/.gitkeep
  frontend/src/features/auth/components/AuthInput.tsx
  frontend/src/features/auth/components/LoginForm.tsx
  frontend/src/features/auth/components/index.ts
  frontend/src/features/auth/types/.gitkeep
  frontend/src/features/auth/types/index.ts
  frontend/src/features/auth/utils/.gitkeep
  frontend/src/features/auth/utils/auth.ts
  frontend/src/features/auth/utils/index.ts
  frontend/src/routes/__root.tsx
  frontend/src/routes/_auth/login/index.tsx
  frontend/src/routes/customer/index.tsx
  frontend/src/routes/helper/index.tsx
  frontend/src/routes/index.tsx
  frontend/src/shared/apis/authMiddleware.ts
  frontend/src/shared/apis/client.ts
  frontend/src/shared/components/EscortCard.tsx
  frontend/src/shared/components/StatusTag.tsx
  frontend/src/shared/types/api/schema.d.ts
  frontend/src/shared/types/statusType.ts
  frontend/src/styles.css
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#209 [BE] Common > S3 이미지 업로드 #199
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/features/customer/components/recruitStep/Final.tsx
  frontend/src/features/customer/components/recruitStep/Profile.tsx
  frontend/src/features/customer/types/recruitFormValues.ts
  frontend/src/features/customer/utils/buildRecruitRequest.ts
  frontend/src/features/helper/components/profileSteps/Region.tsx
  frontend/src/routes/components/index.tsx
  frontend/src/shared/apis/image/postPresignedUrl.ts
  frontend/src/shared/apis/image/putS3Upload.ts
  frontend/src/shared/apis/index.ts
  frontend/src/shared/components/form/PhotoUpload.tsx
  frontend/src/shared/hooks/index.ts
  frontend/src/shared/hooks/useImageUpload.ts
  frontend/src/shared/types/api/schema.d.ts
  frontend/src/shared/types/imageType.ts
  frontend/src/shared/utils/image.ts
  frontend/src/shared/utils/index.ts
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#197 [BE] [SUB] Setting > Swagger에서 Cookie를 통한 인증 #196
  backend/server/src/main/java/com/todoc/server/common/config/SwaggerConfig.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High

#215 [BE] [SUB] Recruit > Recruit History 조회 기능 수정 #214
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitHistoryDetailResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: ♻️ Refactor, Priority: 🔥 High

#224 [BE] [SUB] Route > 외부 TMAP API 호출에 대한 예외 구체화 #222
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitFacadeService.java
  backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapAPICallException.java
  backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapErrorCode.java
  backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapInternalException.java
  backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapParsingException.java
  backend/server/src/main/java/com/todoc/server/external/tmap/service/TMapRouteParser.java
  backend/server/src/main/java/com/todoc/server/external/tmap/service/TMapRouteService.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitFacadeServiceTest.java
Labels: Part: 🛠 BE, Type: ♻️ Refactor, Priority: ⚡ Medium

#226 [BE] [SUB] Recruit > RecruitSimpleResponse에 동행 상태 필드 추가 #225
  backend/server/src/main/java/com/todoc/server/common/enumeration/EscortStatus.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: ♻️ Refactor, Priority: 🔥 High

#229 [BE] [SUB] Helper > 도우미 대시보드 기본 API 테스트코드 작성 #202
  backend/server/src/main/java/com/todoc/server/domain/customer/web/dto/response/PatientSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/EscortMemoUpdateRequest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/report/service/ReportIntegrationTest.java
  backend/server/src/test/resources/sql/data.sql
Labels: Part: 🛠 BE, Type: 🧪 Test, Priority: 🔥 High

#234 [BE] [SUB] Common > API 연결 과정 발생한 버그 수정 #231
  backend/server/src/main/java/com/todoc/server/domain/customer/web/dto/response/PatientSimpleResponse.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/dto/EscortDetailFlatDto.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/ApplicationFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/EscortController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitPaymentResponse.java
  backend/server/src/main/java/com/todoc/server/domain/report/repository/ReportQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/ReportService.java
  backend/server/src/main/java/com/todoc/server/domain/route/entity/Route.java
  backend/server/src/main/java/com/todoc/server/domain/route/entity/RouteLeg.java
  backend/server/src/main/java/com/todoc/server/domain/route/repository/RouteLegRepository.java
  backend/server/src/main/java/com/todoc/server/domain/route/service/RouteLegService.java
  backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteDetailResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
  backend/server/src/test/java/com/todoc/server/domain/report/service/ReportIntegrationTest.java
  backend/server/src/test/resources/sql/data.sql
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#236 [BE] [SUB] Escort > 각 동행별 3시간 전 동행 상태를 변경하는 스케줄링 코드 작성 #228
  backend/server/src/main/java/com/todoc/server/ServerApplication.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitScheduler.java
Labels: Part: 🛠 BE

#245 [BE] [SUB] Route > Route 경로가 필요하지 않은 곳에도 경로를 제공하던 API 문제 해결 #244
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitPaymentResponse.java
  backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteDetailResponse.java
  backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteSimpleResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#250 [BE] [SUB] Dashboard > 도우미가 서버로 보내는 마지막 위치정보 수신 기능 구현 #241
  .github/workflows/backend-pr-ci.yml
  backend/server/src/main/java/com/todoc/server/common/config/RedisConfig.java
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/repository/LocationCacheRepository.java
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/service/LocationService.java
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/controllerv2/LocationController.java
  backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/dto/request/LocationRequest.java
  backend/server/src/main/resources/application-ci.yml
  backend/server/src/test/java/com/todoc/server/IntegrationTestBase.java
  backend/server/src/test/java/com/todoc/server/ServerApplicationTests.java
  backend/server/src/test/java/com/todoc/server/domain/auth/service/AuthIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/ApplicationIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/report/service/ReportIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/review/service/ReviewIntegrationTest.java
Labels: Part: 🛠 BE, Type: ✨ Feature, Priority: 🔥 High

#235 [FE] Customer > API 연동
  frontend/src/features/customer/apis/deleteRecruit.ts
  frontend/src/features/customer/apis/getApplicationListById.ts
  frontend/src/features/customer/apis/getRecruitPayment.ts
  frontend/src/features/customer/apis/getRecruitReportByRecruitId.ts
  frontend/src/features/customer/apis/getRecruitReviewByRecruitId.ts
  frontend/src/features/customer/apis/index.ts
  frontend/src/features/customer/apis/postSelectApplication.ts
  frontend/src/features/customer/components/PaymentCard.tsx
  frontend/src/features/customer/components/ReviewCard.tsx
  frontend/src/features/customer/components/RouteButton.tsx
  frontend/src/features/customer/components/cards/HelperCard.tsx
  frontend/src/features/customer/components/cards/HelperEmptyCard.tsx
  frontend/src/features/customer/components/index.ts
  frontend/src/features/customer/components/recruitStep/Profile.tsx
  frontend/src/features/customer/components/reviewStep/Comment.tsx
  frontend/src/features/customer/components/tabs/DetailTab.tsx
  frontend/src/features/customer/components/tabs/HelperTab.tsx
  frontend/src/features/customer/components/tabs/ReportTab.tsx
  frontend/src/features/customer/types/schemaTypes.ts
  frontend/src/routes/customer/escort/$escortId/$helperId.helper.$applicationId.tsx
  frontend/src/routes/customer/escort/$escortId/completed.tsx
  frontend/src/routes/customer/escort/$escortId/index.tsx
  frontend/src/routes/customer/escort/$escortId/payment.$applicationId.tsx
  frontend/src/routes/customer/index.tsx
  frontend/src/routes/helper/index.tsx
  frontend/src/shared/components/EmptyCard.tsx
  frontend/src/shared/components/Landing.tsx
  frontend/src/shared/components/ProgressIndicator.tsx
  frontend/src/shared/components/TextField/FormInput.tsx
  frontend/src/shared/components/index.ts
  frontend/src/shared/types/api/schema.d.ts
  frontend/src/shared/utils/date.ts
  frontend/src/shared/utils/formatValue.ts
  frontend/src/shared/utils/parseType.ts
Labels: Part: 🌐 FE, Priority: 🔥 High, Type: 🏞️ Publish, 🤝 API 연결

#275 [BE] [SUB] Helper > 환자 프로필이 이미 있는 경우 새로 생성할 수 없도록 제한 #274
  backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperErrorCode.java
  backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperProfileAlreadyCreatedException.java
  backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java
  backend/server/src/main/java/com/todoc/server/domain/route/Coordinate.java
  backend/server/src/main/java/com/todoc/server/external/tmap/service/TMapRouteParser.java
  backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperIntegrationTest.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#278 [BE] [SUB] Helper > 동행 상태 이동에 대한 예외 처리 추가 #277
  backend/server/src/main/java/com/todoc/server/domain/report/exception/ReportAlreadyWrittenException.java
  backend/server/src/main/java/com/todoc/server/domain/report/exception/ReportErrorCode.java
  backend/server/src/main/java/com/todoc/server/domain/report/exception/ReportNotReadyToWriteException.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/ReportFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/report/service/ReportService.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/report/service/ReportFacadeServiceTest.java
  backend/server/src/test/resources/sql/data.sql
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#286 [BE] [SUB] Images > S3 접속 오류 해결 #285
  backend/server/build.gradle.kts
  backend/server/src/main/java/com/todoc/server/common/config/S3Config.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#295 [BE] [SUB] Helper > 자신이 신청한 동행은 도우미로서 검색할 수 없도록 처리 #282
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java
  backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/EscortStatusResponse.java
  backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/dto/response/LocationResponse.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitIntegrationTest.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#299 [FE] Helper > 대시보드 퍼블리시
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/marker-depart.svg
  frontend/src/assets/icons/taxi-called.svg
  frontend/src/assets/icons/taxi-completed.svg
  frontend/src/assets/icons/taxi-failed.svg
  frontend/src/assets/icons/taxi-waiting.svg
  frontend/src/features/dashboard/apis/index.ts
  frontend/src/features/dashboard/apis/patchEscortMemo.ts
  frontend/src/features/dashboard/apis/patchEscortStatusByEscortId.ts
  frontend/src/features/dashboard/apis/postCurrentPosition.ts
  frontend/src/features/dashboard/apis/postLocation.ts
  frontend/src/features/dashboard/components/DashBoardCard.tsx
  frontend/src/features/dashboard/components/Header.tsx
  frontend/src/features/dashboard/components/dashboardIndex/CustomerDashboardLive.tsx
  frontend/src/features/dashboard/components/dashboardIndex/HelperDashboardSearchCard.tsx
  frontend/src/features/dashboard/components/dashboardIndex/HelperDashboardSummary.tsx
  frontend/src/features/dashboard/components/dashboardIndex/HelperDashboardTaxiCard.tsx
  frontend/src/features/dashboard/components/index.ts
  frontend/src/features/dashboard/constants/map.ts
  frontend/src/features/dashboard/hooks/.gitkeep
  frontend/src/features/dashboard/hooks/index.ts
  frontend/src/features/dashboard/hooks/useSSE.ts
  frontend/src/features/dashboard/types/schemaTypes.ts
  frontend/src/features/helper/components/reportStep/Time.tsx
  frontend/src/features/helper/utils/index.ts
  frontend/src/features/helper/utils/map.ts
  frontend/src/routes/dashboard/$escortId/customer/index.tsx
  frontend/src/routes/dashboard/$escortId/customer/prepare.tsx
  frontend/src/routes/dashboard/$escortId/helper/index.tsx
  frontend/src/routes/dashboard/$escortId/helper/prepare.tsx
  frontend/src/routes/dashboard/$escortId/map.tsx
  frontend/src/routes/helper/escort/$escortId/report.$step.tsx
  frontend/src/routes/map.tsx
  frontend/src/shared/components/FloatingButton.tsx
  frontend/src/shared/components/SlideButton.tsx
  frontend/src/shared/components/index.ts
  frontend/src/shared/hooks/useMap.ts
  frontend/src/shared/types/api/schema.d.ts
  frontend/src/shared/types/map.ts
  frontend/src/shared/types/tmap.ts
  frontend/src/shared/utils/date.ts
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: 🔥 High

#313 [FE] QA > 메타데이터 수정 #310
  frontend/index.html
  frontend/public/browserconfig.xml
  frontend/public/images/open-graph.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/public/sitemap.xml
Labels: Part: 🌐 FE, Type: ✨ Feature, Priority: ⚡ Medium

#316 [FE] QA > 화면 레이아웃 수정 #314
  frontend/public/images/qrcode.webp
  frontend/src/shared/components/Landing.tsx
  frontend/src/shared/components/Tabs.tsx
  frontend/src/shared/components/TopAppBar.tsx
  frontend/src/shared/layouts/FormLayout.tsx
  frontend/src/shared/layouts/PageLayout.tsx
  frontend/src/shared/layouts/RootLayout.tsx
  frontend/src/styles.css
Labels: Part: 🌐 FE, Type: 🐞 Fix, Priority: ⚡ Medium

#322 [BE] [SUB] QA > 1차 QA 수정사항 반영 #321
  backend/server/src/main/java/com/todoc/server/common/config/TimeConfig.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortScheduledFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitScheduler.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java
  backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteSimpleResponse.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#323 [FE] QA 반영
  frontend/src/features/customer/apis/index.ts
  frontend/src/features/customer/components/recruitStep/EscortRoute.tsx
  frontend/src/features/customer/components/recruitStep/Profile.tsx
  frontend/src/features/customer/components/recruitStep/Request.tsx
  frontend/src/features/customer/components/recruitStep/Time.tsx
  frontend/src/features/customer/components/reviewStep/Comment.tsx
  frontend/src/features/customer/components/tabs/DetailTab.tsx
  frontend/src/features/customer/types/recruitFormValues.ts
  frontend/src/features/helper/components/tabs/ReportTab.tsx
  frontend/src/routes/customer/escort/$escortId/$helperId.review.$step.tsx
  frontend/src/routes/dashboard/$escortId/customer/index.tsx
  frontend/src/routes/dashboard/$escortId/helper/index.tsx
  frontend/src/routes/dashboard/$escortId/map.tsx
  frontend/src/routes/helper/application/$escortId/index.tsx
  frontend/src/routes/helper/application/index.tsx
  frontend/src/routes/helper/index.tsx
  frontend/src/shared/components/TextField/FormInput.tsx
  frontend/src/shared/components/modal/TermsBottomSheet.tsx
  frontend/src/shared/layouts/PageLayout.tsx
Labels: Part: 🌐 FE, Type: 🐞 Fix, Priority: 🔥 High

#344 [BE] [SUB] Dashboard > WebSocket 연결 관련 수정 및 SSE 관련 코드 제외 #343
  backend/server/src/main/java/com/todoc/server/common/config/RedisConfig.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/LocationCacheRepository.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/RedisLocationScriptsConfig.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/LocationService.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/NchanPublisher.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/RealtimeFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/RedisSubscriber.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/SseEmitterManager.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/WebSocketFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/WebSocketSessionRegistry.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/PresenceController.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/RealtimeController.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/WebSocketAuthHandshakeInterceptor.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/WebSocketRealtimeHandler.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/WsDiagController.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortServiceTest.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#348 [BE] [SUB] Dashboard > 위치 변화 없어도 30초에 한 번은 새로운 위치 정보 전송하도록 수정 #347
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/LocationCacheRepository.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/RedisLocationScriptsConfig.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#354 [BE] [SUB] Dashboard > 레디스에 문자열 "null"이 저장되는 문제 해결 #353
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/LocationCacheRepository.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/RedisLocationScriptsConfig.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/RealtimeFacadeService.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High

#367 [BE] [SUB] Dashboard > 메세지 전송 비동기 처리 #366
  backend/server/src/main/java/com/todoc/server/common/config/AsyncConfig.java
  backend/server/src/main/java/com/todoc/server/common/util/TransactionUtils.java
  backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/exception/RealtimeLocationNotUpdatedException.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/LocationCacheRepository.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/RedisLocationScriptsConfig.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/repository/dto/LocationUpdateResult.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/NchanPublisher.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/RedisSubscriber.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/WebSocketFacadeService.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/service/WebSocketSessionRegistry.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/PresenceController.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/WebSocketAuthHandshakeInterceptor.java
  backend/server/src/main/java/com/todoc/server/domain/realtime/web/controller/WebSocketRealtimeHandler.java
  backend/server/src/test/java/com/todoc/server/domain/escort/service/escort/EscortServiceTest.java
Labels: Part: 🛠 BE, Type: 🐞 Fix, Priority: 🔥 High
